import { aboutPageUpdateSchema } from "@/lib/validations/about";
import { blogPostCreateSchema } from "@/lib/validations/blog";
import { certificationCreateSchema } from "@/lib/validations/certification";
import { educationCreateSchema } from "@/lib/validations/education";
import { experienceCreateSchema } from "@/lib/validations/experience";
import { heroUpdateSchema } from "@/lib/validations/hero";
import { projectCreateSchema } from "@/lib/validations/project";
import { siteSettingsUpdateSchema } from "@/lib/validations/settings";
import { skillCreateSchema } from "@/lib/validations/skill";

import type { EntityConfig } from "./types";

export const entityConfigs: Record<string, EntityConfig> = {
  projects: {
    label: "Project",
    pluralLabel: "Projects",
    prismaModel: "project",
    queryKey: ["admin", "projects"],
    uniqueKey: { type: "single", field: "slug" },
    arrayFields: ["techTags"],
    numericFields: ["displayOrder"],
    jsonFields: ["images"],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/projects", "/"],
    detailPathPrefix: "/projects",
    importSchema: projectCreateSchema,
    orderBy: { displayOrder: "asc" },
  },
  blog: {
    label: "Blog Post",
    pluralLabel: "Blog Posts",
    prismaModel: "blogPost",
    queryKey: ["admin", "blog"],
    uniqueKey: { type: "single", field: "slug" },
    arrayFields: ["tags"],
    numericFields: ["readTime"],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/blog", "/"],
    detailPathPrefix: "/blog",
    importSchema: blogPostCreateSchema,
    orderBy: { createdAt: "desc" },
  },
  experience: {
    label: "Experience",
    pluralLabel: "Experience",
    prismaModel: "experience",
    queryKey: ["admin", "experience"],
    uniqueKey: { type: "compound", fields: ["company", "role"] },
    arrayFields: ["highlights", "highlightsJa", "techTags"],
    numericFields: ["displayOrder"],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/about"],
    importSchema: experienceCreateSchema,
    orderBy: { displayOrder: "asc" },
  },
  education: {
    label: "Education",
    pluralLabel: "Education",
    prismaModel: "education",
    queryKey: ["admin", "education"],
    uniqueKey: { type: "compound", fields: ["institution", "degree"] },
    arrayFields: [],
    numericFields: ["displayOrder"],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/about"],
    importSchema: educationCreateSchema,
    orderBy: { displayOrder: "asc" },
  },
  skills: {
    label: "Skill",
    pluralLabel: "Skills",
    prismaModel: "skill",
    queryKey: ["admin", "skills"],
    uniqueKey: { type: "single", field: "name" },
    arrayFields: [],
    numericFields: ["displayOrder"],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/about"],
    importSchema: skillCreateSchema,
    orderBy: { displayOrder: "asc" },
  },
  certifications: {
    label: "Certification",
    pluralLabel: "Certifications",
    prismaModel: "certification",
    queryKey: ["admin", "certifications"],
    uniqueKey: { type: "compound", fields: ["name", "issuer"] },
    arrayFields: [],
    numericFields: ["displayOrder"],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: false,
    revalidatePaths: ["/about"],
    importSchema: certificationCreateSchema,
    orderBy: { displayOrder: "asc" },
  },
  messages: {
    label: "Message",
    pluralLabel: "Messages",
    prismaModel: "contactMessage",
    queryKey: ["messages"],
    uniqueKey: null,
    arrayFields: [],
    numericFields: [],
    jsonFields: [],
    excludeFromExport: ["id"],
    isSingleton: false,
    formats: ["json", "csv"],
    importDisabled: true,
    revalidatePaths: [],
    importSchema: {} as never,
    orderBy: { createdAt: "desc" },
  },
  hero: {
    label: "Hero",
    pluralLabel: "Hero",
    prismaModel: "hero",
    queryKey: ["admin", "hero"],
    uniqueKey: null,
    arrayFields: [],
    numericFields: [],
    jsonFields: ["ctaButtons", "ctaButtonsJa"],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: true,
    formats: ["json"],
    importDisabled: false,
    revalidatePaths: ["/"],
    importSchema: heroUpdateSchema,
    orderBy: {},
  },
  about: {
    label: "About",
    pluralLabel: "About",
    prismaModel: "aboutPage",
    queryKey: ["admin", "about"],
    uniqueKey: null,
    arrayFields: [],
    numericFields: [],
    jsonFields: [],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: true,
    formats: ["json"],
    importDisabled: false,
    revalidatePaths: ["/", "/about"],
    importSchema: aboutPageUpdateSchema,
    orderBy: {},
  },
  settings: {
    label: "Settings",
    pluralLabel: "Settings",
    prismaModel: "siteSettings",
    queryKey: ["admin", "settings"],
    uniqueKey: null,
    arrayFields: [],
    numericFields: [],
    jsonFields: ["socialLinks"],
    excludeFromExport: ["id", "createdAt", "updatedAt"],
    isSingleton: true,
    formats: ["json"],
    importDisabled: false,
    revalidatePaths: ["/"],
    importSchema: siteSettingsUpdateSchema,
    orderBy: {},
  },
};
